learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index , name ='index'),
    path('myapp/',include('myapp.urls')),



        ]

learning_templates/myapp/urls.py
from django.urls import path
from myapp import views


# temlpate tagging 
app_name ='myapp'

urlpatterns= [
 
    path(r'relative/',views.relative,name = 'relative'),
    path(r'',views.index1 , name ='index1'),
    path(r'other/',views.other,name = 'other'),



]

learning_templates/myapp/models.py
from django.db import models

# Create your models here.

learning_templates/myapp/views.py
from django.shortcuts import render


def index(request):

    # 3la khater temlpate fiter 
    context_dict = {'text':'hello world','number':100 }
    return render(request,'basic_app/index.html',context_dict)



def index1(request):
    return render(request,'basic_app/index1.html')
    

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_urls.html')


  

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title> base </title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>

<nav class="navbar navbar-default navbar-static-top">

  <div class="container">

<ul class="nav navbar-nav ">
     <li><a class="navbar-brand" href="{% url 'index' %}">HOme</a></li>
     <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
     <li><a class="navbar-link" href="{% url 'myapp:other' %}">Other</a></li>
    
</ul>
    </div>
  </div>
</nav>



<div class="container"> 

     {% block body_block %}
     
     <h1>  FROM BASE  " intrene the block non inhernteced" </h1>
    <!-- Anything inherttede if you extend ! -->
    {% endblock %}


</div>

</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}

{% block body_block %}

<h1> frome index home PAGE !</h1>

hna yji lel filterr >>>
<h2>{{text|cut:'hello'}}</h2> 
<br>
<!--<h3>{{number|add:"33"}}</h3>-->
<h3>{{number|add:"33"}}</h3>


{% endblock %} 

learning_templates/templates/basic_app/index1.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title> my page home  </title>
</head>
<body>
	<h1> Welcome my apps ! !!</h1>

</body>
</html>

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}

{% block body_block %}

<h1>  heloo from outher </h1>
<a href="{% url 'myapp:relative' %}"> back to Relative Page !!</a>

{% endblock %} 

learning_templates/templates/basic_app/relative_urls.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title> to relative yrls  </title>
</head>
<body>
<h1> welcome to  relative URLS  </h1>
<!-- <a href="basic_app/other.html"> the other page </a>       normalmenet ndiro hak -->
<a href="{% url 'myapp:other' %}"> the other Page !</a>
  <br>
<a href="{% url 'admin:index' %}"> Go to Admin</a>
<br>
<a href="{% url 'index' %}"> From my APP !</a>

</body>
</html>  